"""The digest's CHROME, in nine languages. Section headings, badges, footers.

This is not a translation of anyone's mail: subjects, senders, the model's
notes and its drafted replies all stay exactly as they arrived or as the
model wrote them. What the model writes in is set by `draft_style.language`,
which this does not touch. `language` in config.yaml only decides the words
mailtriage itself puts around your mail.

Adding a key means adding it to EVERY language below -- `tests/test_strings.py`
fails otherwise. An honest English word in a table of translations is better
than a key that renders as `[missing]`, so translate on the way in, don't
leave a hole.

Counts that need a plural take the fragment form: `days_one`/`days_other` etc.
render "1 day" / "3 days", and the sentence that uses them interpolates the
finished fragment. That keeps every language's own agreement rules inside its
own row instead of in Python.
"""

from __future__ import annotations

import sys
from typing import TYPE_CHECKING

if TYPE_CHECKING:  # config.py imports this module lazily -- never at module scope, or it's a cycle
    from mailtriage.config import Config

FALLBACK = "en"

STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "act_read": "{a} to act · {r} to read",
        "needs_action": "Needs action",
        "section_group": "{section} · {group}",
        "overdue": "Overdue",
        "today": "Today",
        "this_week": "This week",
        "later": "Later",
        "no_date": "No date",
        "still_waiting": "Still waiting on you",
        "worth_reading": "Worth reading",
        "all_day": "All day",
        "invite_in_inbox": "invite in your inbox: #{n}",
        "draft_reply": "Draft reply",
        "draft_full": "A fuller version is in Drafts.",
        "due": "Due {date}",
        "add_to_calendar": "Add to Google Calendar",
        "waiting": "waiting {days}",
        "still_open": "still open",
        "carried_footer": "Clears when you reply, archive, or remove the {label} label in Gmail.",
        "noise_this_week": "Noise this week",
        "unsubscribe": "Unsubscribe",
        "digest_footer": "Triaged by mailtriage from your own inboxes.",
        "your_week": "Your week",
        "week_handled": "{n} handled",
        "week_done": "{n} marked done",
        "week_open": "{n} still open",
        "count_replied": "{n} replied",
        "count_archived": "{n} archived",
        "count_open": "{n} open",
        "nothing_open": "Nothing open.",
        "replied": "Replied",
        "archived": "Archived",
        "patterns": "Patterns",
        "weekly_footer": "Open items clear when you reply, archive, or remove the {label} label.",
        "saved": (
            "This week mailtriage handled {messages} and drafted {replies} — roughly {minutes} "
            "you did not spend on your inbox (an estimate, not a measurement)."
        ),
        "days_one": "{n} day",
        "days_other": "{n} days",
        "msgs_one": "{n} message",
        "msgs_other": "{n} messages",
        "replies_one": "{n} reply",
        "replies_other": "{n} replies",
        "minutes_one": "{n} minute",
        "minutes_other": "{n} minutes",
    },
    "es": {
        "act_read": "{a} por hacer · {r} por leer",
        "needs_action": "Requiere acción",
        "section_group": "{section} · {group}",
        "overdue": "Atrasado",
        "today": "Hoy",
        "this_week": "Esta semana",
        "later": "Más adelante",
        "no_date": "Sin fecha",
        "still_waiting": "Siguen esperándote",
        "worth_reading": "Vale la pena leer",
        "all_day": "Todo el día",
        "invite_in_inbox": "invitación en tu bandeja: #{n}",
        "draft_reply": "Borrador de respuesta",
        "draft_full": "Hay una versión más completa en Borradores.",
        "due": "Vence {date}",
        "add_to_calendar": "Añadir a Google Calendar",
        "waiting": "esperando {days}",
        "still_open": "sigue abierto",
        "carried_footer": "Desaparece cuando respondes, archivas o quitas la etiqueta {label} en Gmail.",
        "noise_this_week": "Ruido de esta semana",
        "unsubscribe": "Darse de baja",
        "digest_footer": "Clasificado por mailtriage desde tus propias bandejas.",
        "your_week": "Tu semana",
        "week_handled": "{n} resueltos",
        "week_done": "{n} marcados como hechos",
        "week_open": "{n} siguen abiertos",
        "count_replied": "{n} respondidos",
        "count_archived": "{n} archivados",
        "count_open": "{n} abiertos",
        "nothing_open": "Nada abierto.",
        "replied": "Respondidos",
        "archived": "Archivados",
        "patterns": "Patrones",
        "weekly_footer": "Los pendientes desaparecen cuando respondes, archivas o quitas la etiqueta {label}.",
        "saved": (
            "Esta semana mailtriage gestionó {messages} y redactó {replies}: unos {minutes} "
            "que no dedicaste a tu bandeja (una estimación, no una medición)."
        ),
        "days_one": "{n} día",
        "days_other": "{n} días",
        "msgs_one": "{n} mensaje",
        "msgs_other": "{n} mensajes",
        "replies_one": "{n} respuesta",
        "replies_other": "{n} respuestas",
        "minutes_one": "{n} minuto",
        "minutes_other": "{n} minutos",
    },
    "fr": {
        "act_read": "{a} à traiter · {r} à lire",
        "needs_action": "Action requise",
        "section_group": "{section} · {group}",
        "overdue": "En retard",
        "today": "Aujourd'hui",
        "this_week": "Cette semaine",
        "later": "Plus tard",
        "no_date": "Sans date",
        "still_waiting": "On attend toujours votre réponse",
        "worth_reading": "À lire",
        "all_day": "Toute la journée",
        "invite_in_inbox": "invitation dans votre boîte : #{n}",
        "draft_reply": "Brouillon de réponse",
        "draft_full": "Une version plus complète est dans les brouillons.",
        "due": "Échéance {date}",
        "add_to_calendar": "Ajouter à Google Agenda",
        "waiting": "en attente depuis {days}",
        "still_open": "toujours ouvert",
        "carried_footer": "Disparaît quand vous répondez, archivez ou retirez le libellé {label} dans Gmail.",
        "noise_this_week": "Bruit de la semaine",
        "unsubscribe": "Se désabonner",
        "digest_footer": "Trié par mailtriage depuis vos propres boîtes.",
        "your_week": "Votre semaine",
        "week_handled": "{n} traités",
        "week_done": "{n} marqués comme faits",
        "week_open": "{n} encore ouverts",
        "count_replied": "{n} répondus",
        "count_archived": "{n} archivés",
        "count_open": "{n} ouverts",
        "nothing_open": "Rien en attente.",
        "replied": "Répondus",
        "archived": "Archivés",
        "patterns": "Tendances",
        "weekly_footer": "Les éléments ouverts disparaissent quand vous répondez, archivez ou retirez le libellé {label}.",
        "saved": (
            "Cette semaine, mailtriage a traité {messages} et rédigé {replies} — environ {minutes} "
            "que vous n'avez pas passées dans votre boîte (une estimation, pas une mesure)."
        ),
        "days_one": "{n} jour",
        "days_other": "{n} jours",
        "msgs_one": "{n} message",
        "msgs_other": "{n} messages",
        "replies_one": "{n} réponse",
        "replies_other": "{n} réponses",
        "minutes_one": "{n} minute",
        "minutes_other": "{n} minutes",
    },
    "de": {
        "act_read": "{a} zu erledigen · {r} zu lesen",
        "needs_action": "Erfordert Handeln",
        "section_group": "{section} · {group}",
        "overdue": "Überfällig",
        "today": "Heute",
        "this_week": "Diese Woche",
        "later": "Später",
        "no_date": "Ohne Datum",
        "still_waiting": "Wartet weiter auf Sie",
        "worth_reading": "Lesenswert",
        "all_day": "Ganztägig",
        "invite_in_inbox": "Einladung im Posteingang: #{n}",
        "draft_reply": "Antwortentwurf",
        "draft_full": "Eine ausführlichere Fassung liegt in den Entwürfen.",
        "due": "Fällig {date}",
        "add_to_calendar": "Zu Google Kalender hinzufügen",
        "waiting": "wartet seit {days}",
        "still_open": "noch offen",
        "carried_footer": "Verschwindet, sobald Sie antworten, archivieren oder das Label {label} in Gmail entfernen.",
        "noise_this_week": "Rauschen dieser Woche",
        "unsubscribe": "Abmelden",
        "digest_footer": "Sortiert von mailtriage aus Ihren eigenen Postfächern.",
        "your_week": "Ihre Woche",
        "week_handled": "{n} erledigt",
        "week_done": "{n} als erledigt markiert",
        "week_open": "{n} noch offen",
        "count_replied": "{n} beantwortet",
        "count_archived": "{n} archiviert",
        "count_open": "{n} offen",
        "nothing_open": "Nichts offen.",
        "replied": "Beantwortet",
        "archived": "Archiviert",
        "patterns": "Muster",
        "weekly_footer": "Offene Einträge verschwinden, sobald Sie antworten, archivieren oder das Label {label} entfernen.",
        "saved": (
            "Diese Woche hat mailtriage {messages} sortiert und {replies} entworfen — etwa {minutes}, "
            "die Sie nicht im Postfach verbracht haben (eine Schätzung, keine Messung)."
        ),
        "days_one": "{n} Tag",
        "days_other": "{n} Tagen",
        "msgs_one": "{n} Nachricht",
        "msgs_other": "{n} Nachrichten",
        "replies_one": "{n} Antwort",
        "replies_other": "{n} Antworten",
        "minutes_one": "{n} Minute",
        "minutes_other": "{n} Minuten",
    },
    "pt": {
        "act_read": "{a} a tratar · {r} a ler",
        "needs_action": "Requer ação",
        "section_group": "{section} · {group}",
        "overdue": "Atrasado",
        "today": "Hoje",
        "this_week": "Esta semana",
        "later": "Mais tarde",
        "no_date": "Sem data",
        "still_waiting": "Continuam à sua espera",
        "worth_reading": "Vale a pena ler",
        "all_day": "Todo o dia",
        "invite_in_inbox": "convite na sua caixa: #{n}",
        "draft_reply": "Rascunho de resposta",
        "draft_full": "Há uma versão mais completa nos rascunhos.",
        "due": "Prazo {date}",
        "add_to_calendar": "Adicionar ao Google Agenda",
        "waiting": "à espera há {days}",
        "still_open": "ainda aberto",
        "carried_footer": "Desaparece quando responde, arquiva ou remove a etiqueta {label} no Gmail.",
        "noise_this_week": "Ruído desta semana",
        "unsubscribe": "Cancelar subscrição",
        "digest_footer": "Triado pelo mailtriage a partir das suas próprias caixas.",
        "your_week": "A sua semana",
        "week_handled": "{n} tratados",
        "week_done": "{n} marcados como feitos",
        "week_open": "{n} ainda abertos",
        "count_replied": "{n} respondidos",
        "count_archived": "{n} arquivados",
        "count_open": "{n} abertos",
        "nothing_open": "Nada aberto.",
        "replied": "Respondidos",
        "archived": "Arquivados",
        "patterns": "Padrões",
        "weekly_footer": "Os itens abertos desaparecem quando responde, arquiva ou remove a etiqueta {label}.",
        "saved": (
            "Esta semana o mailtriage tratou {messages} e redigiu {replies} — cerca de {minutes} "
            "que não passou na sua caixa de entrada (uma estimativa, não uma medição)."
        ),
        "days_one": "{n} dia",
        "days_other": "{n} dias",
        "msgs_one": "{n} mensagem",
        "msgs_other": "{n} mensagens",
        "replies_one": "{n} resposta",
        "replies_other": "{n} respostas",
        "minutes_one": "{n} minuto",
        "minutes_other": "{n} minutos",
    },
    "it": {
        "act_read": "{a} da gestire · {r} da leggere",
        "needs_action": "Richiede azione",
        "section_group": "{section} · {group}",
        "overdue": "In ritardo",
        "today": "Oggi",
        "this_week": "Questa settimana",
        "later": "Più avanti",
        "no_date": "Senza data",
        "still_waiting": "Ti stanno ancora aspettando",
        "worth_reading": "Da leggere",
        "all_day": "Tutto il giorno",
        "invite_in_inbox": "invito nella tua posta: #{n}",
        "draft_reply": "Bozza di risposta",
        "draft_full": "Una versione più completa è nelle bozze.",
        "due": "Scadenza {date}",
        "add_to_calendar": "Aggiungi a Google Calendar",
        "waiting": "in attesa da {days}",
        "still_open": "ancora aperto",
        "carried_footer": "Sparisce quando rispondi, archivi o togli l'etichetta {label} in Gmail.",
        "noise_this_week": "Rumore di questa settimana",
        "unsubscribe": "Annulla iscrizione",
        "digest_footer": "Smistato da mailtriage dalle tue caselle.",
        "your_week": "La tua settimana",
        "week_handled": "{n} gestiti",
        "week_done": "{n} segnati come fatti",
        "week_open": "{n} ancora aperti",
        "count_replied": "{n} con risposta",
        "count_archived": "{n} archiviati",
        "count_open": "{n} aperti",
        "nothing_open": "Niente in sospeso.",
        "replied": "Con risposta",
        "archived": "Archiviati",
        "patterns": "Ricorrenze",
        "weekly_footer": "Gli elementi aperti spariscono quando rispondi, archivi o togli l'etichetta {label}.",
        "saved": (
            "Questa settimana mailtriage ha gestito {messages} e scritto {replies} — circa {minutes} "
            "che non hai passato nella posta (una stima, non una misura)."
        ),
        "days_one": "{n} giorno",
        "days_other": "{n} giorni",
        "msgs_one": "{n} messaggio",
        "msgs_other": "{n} messaggi",
        "replies_one": "{n} risposta",
        "replies_other": "{n} risposte",
        "minutes_one": "{n} minuto",
        "minutes_other": "{n} minuti",
    },
    "nl": {
        "act_read": "{a} te doen · {r} te lezen",
        "needs_action": "Vraagt actie",
        "section_group": "{section} · {group}",
        "overdue": "Te laat",
        "today": "Vandaag",
        "this_week": "Deze week",
        "later": "Later",
        "no_date": "Zonder datum",
        "still_waiting": "Wachten nog op je",
        "worth_reading": "De moeite waard",
        "all_day": "Hele dag",
        "invite_in_inbox": "uitnodiging in je inbox: #{n}",
        "draft_reply": "Conceptantwoord",
        "draft_full": "Een uitgebreidere versie staat in Concepten.",
        "due": "Deadline {date}",
        "add_to_calendar": "Toevoegen aan Google Agenda",
        "waiting": "wacht al {days}",
        "still_open": "nog open",
        "carried_footer": "Verdwijnt zodra je antwoordt, archiveert of het label {label} in Gmail verwijdert.",
        "noise_this_week": "Ruis van deze week",
        "unsubscribe": "Afmelden",
        "digest_footer": "Gesorteerd door mailtriage vanuit je eigen mailboxen.",
        "your_week": "Jouw week",
        "week_handled": "{n} afgehandeld",
        "week_done": "{n} als klaar gemarkeerd",
        "week_open": "{n} nog open",
        "count_replied": "{n} beantwoord",
        "count_archived": "{n} gearchiveerd",
        "count_open": "{n} open",
        "nothing_open": "Niets open.",
        "replied": "Beantwoord",
        "archived": "Gearchiveerd",
        "patterns": "Patronen",
        "weekly_footer": "Open items verdwijnen zodra je antwoordt, archiveert of het label {label} verwijdert.",
        "saved": (
            "Deze week verwerkte mailtriage {messages} en schreef {replies} — ongeveer {minutes} "
            "die je niet aan je inbox kwijt was (een schatting, geen meting)."
        ),
        "days_one": "{n} dag",
        "days_other": "{n} dagen",
        "msgs_one": "{n} bericht",
        "msgs_other": "{n} berichten",
        "replies_one": "{n} antwoord",
        "replies_other": "{n} antwoorden",
        "minutes_one": "{n} minuut",
        "minutes_other": "{n} minuten",
    },
    "hi": {
        "act_read": "{a} पर कार्रवाई · {r} पढ़ने को",
        "needs_action": "कार्रवाई चाहिए",
        "section_group": "{section} · {group}",
        "overdue": "समय बीत चुका",
        "today": "आज",
        "this_week": "इस हफ़्ते",
        "later": "बाद में",
        "no_date": "कोई तारीख़ नहीं",
        "still_waiting": "अब भी आपका इंतज़ार",
        "worth_reading": "पढ़ने लायक",
        "all_day": "पूरे दिन",
        "invite_in_inbox": "न्योता आपके इनबॉक्स में: #{n}",
        "draft_reply": "जवाब का मसौदा",
        "draft_full": "ज़्यादा विस्तृत मसौदा ड्राफ़्ट में है।",
        "due": "नियत {date}",
        "add_to_calendar": "Google कैलेंडर में जोड़ें",
        "waiting": "{days} से इंतज़ार",
        "still_open": "अब भी बाकी",
        "carried_footer": "जवाब देने, संग्रह करने या Gmail में {label} लेबल हटाने पर यह चला जाएगा।",
        "noise_this_week": "इस हफ़्ते का शोर",
        "unsubscribe": "सदस्यता छोड़ें",
        "digest_footer": "mailtriage ने आपके ही इनबॉक्स से छाँटा।",
        "your_week": "आपका हफ़्ता",
        "week_handled": "{n} निपटाए",
        "week_done": "{n} पूरे किए गए",
        "week_open": "{n} अब भी बाकी",
        "count_replied": "{n} के जवाब दिए",
        "count_archived": "{n} संग्रहित",
        "count_open": "{n} बाकी",
        "nothing_open": "कुछ भी बाकी नहीं।",
        "replied": "जवाब दिए",
        "archived": "संग्रहित",
        "patterns": "पैटर्न",
        "weekly_footer": "बाकी आइटम जवाब देने, संग्रह करने या {label} लेबल हटाने पर चले जाएँगे।",
        "saved": (
            "इस हफ़्ते mailtriage ने {messages} छाँटे और {replies} लिखे — करीब {minutes} "
            "जो आपने इनबॉक्स में नहीं बिताए (यह अनुमान है, माप नहीं)।"
        ),
        "days_one": "{n} दिन",
        "days_other": "{n} दिनों",
        "msgs_one": "{n} संदेश",
        "msgs_other": "{n} संदेश",
        "replies_one": "{n} जवाब",
        "replies_other": "{n} जवाब",
        "minutes_one": "{n} मिनट",
        "minutes_other": "{n} मिनट",
    },
    "ja": {
        "act_read": "対応 {a} 件 · 一読 {r} 件",
        "needs_action": "要対応",
        "section_group": "{section} · {group}",
        "overdue": "期限切れ",
        "today": "今日",
        "this_week": "今週",
        "later": "後で",
        "no_date": "期日なし",
        "still_waiting": "まだ待たれています",
        "worth_reading": "読む価値あり",
        "all_day": "終日",
        "invite_in_inbox": "受信トレイに招待: #{n}",
        "draft_reply": "返信の下書き",
        "draft_full": "より詳しい下書きが下書きフォルダにあります。",
        "due": "期限 {date}",
        "add_to_calendar": "Google カレンダーに追加",
        "waiting": "{days}待ち",
        "still_open": "未対応",
        "carried_footer": "返信・アーカイブ、または Gmail で {label} ラベルを外すと消えます。",
        "noise_this_week": "今週のノイズ",
        "unsubscribe": "配信停止",
        "digest_footer": "mailtriage があなた自身の受信トレイから仕分けしました。",
        "your_week": "今週のまとめ",
        "week_handled": "{n} 件対応済み",
        "week_done": "{n} 件を完了に",
        "week_open": "{n} 件が未対応",
        "count_replied": "{n} 件返信",
        "count_archived": "{n} 件アーカイブ",
        "count_open": "{n} 件未対応",
        "nothing_open": "未対応はありません。",
        "replied": "返信済み",
        "archived": "アーカイブ済み",
        "patterns": "傾向",
        "weekly_footer": "未対応の項目は、返信・アーカイブ、または {label} ラベルを外すと消えます。",
        "saved": (
            "今週 mailtriage は{messages}を仕分けし、{replies}を下書きしました — 受信トレイに費やさずに済んだ"
            "のはおよそ{minutes}です（実測ではなく概算）。"
        ),
        "days_one": "{n}日",
        "days_other": "{n}日",
        "msgs_one": "{n}件のメッセージ",
        "msgs_other": "{n}件のメッセージ",
        "replies_one": "{n}件の返信",
        "replies_other": "{n}件の返信",
        "minutes_one": "{n}分",
        "minutes_other": "{n}分",
    },
}

LANGUAGES: tuple[str, ...] = tuple(STRINGS)


def base_code(language: str) -> str:
    """BCP-47 down to the base code this table is keyed by: "pt-BR" -> "pt"."""
    return language.strip().replace("_", "-").split("-")[0].lower()


def known(language: str) -> bool:
    return base_code(language) in STRINGS


def t(cfg: Config, key: str, **fmt: object) -> str:
    """One chrome string in `cfg.language`, falling back to English for an
    unknown language (config.py has already warned about that) and for a key
    a language somehow lacks. Pass `n=` for a key with `_one`/`_other` forms
    and the right one is chosen."""
    table = STRINGS.get(base_code(cfg.language), STRINGS[FALLBACK])
    if key not in table and f"{key}_other" in table:
        key = f"{key}_one" if fmt.get("n") == 1 else f"{key}_other"
    text = table.get(key) or STRINGS[FALLBACK].get(key, key)
    try:
        return text.format(**fmt)
    except (KeyError, IndexError):  # a translation with a stray brace must not break the digest
        print(f"mailtriage: bad format in string {key!r}, using it as-is", file=sys.stderr)
        return text
